### PR TITLE
added confirmation for clear function

### PR DESCRIPTION
**Pull request by Csad**
clear button confirmation for patron check in

### CODE REVIEW

**Comment by krishnaglick** [comment]
Look at this diff. Oh god how I hate Visual Studio.

**Comment by krishnaglick** [comment]
Why'd you close w/o merge?

**Comment by Csad** [comment]
my bad i thought the diff would mess things up based on your first comment Lol

**Comment by krishnaglick** [comment]
No, we'll fix & merge it Sunday. Sublime has a reindent function that makes this super easy.

**Pull request merged**
